---
title: "ESM 244 Lab 1"
author: "Heather Luedke"
date: "2023-01-13"
output: html_document
---

```{r setup, include=TRUE, echo = TRUE, warning = FALSE, message = FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)

library(tidyverse)
library(here) 
library(sf) #spatial data
library(tmap) #visualize map data 
```

```{r}
sf_trees <- read_csv(here("data", "sf_trees", "sf_trees.csv"))
#summary(sf_trees)
#names(sf_trees)
#sf_trees %>% group_by(legal_status) %>% summarize(tree_count = n())
top_5_status <- sf_trees %>% 
  group_by(legal_status) %>% 
  summarize(tree_count = n()) %>%
  slice_max(tree_count, n = 5) %>% #find the values of this variable that are the maximum and slice out the top 5 in this case 
  arrange(-tree_count) #ascending order, or -tree_count would be decending order 
  
ggplot(data = top_5_status, aes(x = fct_reorder(legal_status, tree_count), y = tree_count)) + #reorder legal status by tree count 
  geom_col() + 
  labs(y = "Tree count", x = "Legal status") + 
  coord_flip() + 
  theme_minimal()
```
### Keep observations where legal status is "Permitted site" and caretaker is "MTA" 

```{r}
#sf_trees$legal_status %>% unique()
permitted_mta <- sf_trees %>% 
  filter(legal_status == "Permitted Site", caretaker == "MTA")
```

### Keep Blackwood Acacia trees, keep only legal_status, date, latitude, longitude columns

```{r}
blackwood_acacia <- sf_trees %>% 
  filter(str_detect(species, "Blackwood Acacia")) %>%  #take a look in this column if you detect this particular pattern
  select(legal_status, date, latitude, longitude) 

#make a plot of sf acacia 

ggplot(data = blackwood_acacia, aes(x = longitude, y = latitude)) + 
  geom_point()
```
### use tidyr::separate() to separate one column into multiple; use tidyr:unite() to rejoin 

```{r}
sf_trees_sep <- sf_trees %>% 
  separate(species, into = c("spp_scientific", "spp_common"), sep = " :: ") 

sf_trees_unite <- sf_trees %>% 
  unite("id_status", tree_id:species, sep = "_NEW_") # or could be tree_id, species, caretaker, etc
```
### make some actual maps 

```{r}
blackwood_acacia_sf <- blackwood_acacia %>% 
  drop_na(longitude, latitude) %>% 
  st_as_sf(coords = c("longitude", "latitude")) #take spatial and temporal data to turn into a geometry feature 

#now we need to set a coordinate system for this (could be like meters north and east or something) 
st_crs(blackwood_acacia_sf) <- 4326 #indicates latitude and longitude coordinate reference system 

ggplot(data = blackwood_acacia_sf) + 
  geom_sf(color = "dark green") + 
  theme_minimal()
```

### read in SF streets data 
```{r}
sf_map_sf <- read_sf(here("data", "sf_map", "tl_2017_06075_roads.shp")) %>% 
  st_transform(4326)

st_crs(sf_map_sf) #now need to transform lat and long 4326 to match with the 4269 below 
```

```{r}
ggplot() + 
  geom_sf(data = sf_map_sf, size = 0.1, color = "dark gray") +
  geom_sf(data = blackwood_acacia_sf, color = "red", size = 0.5) +
  theme_void() + 
  labs(title = "Blackwood acacias in San Francisco") #san francisco map in simple feature format 
```

### interactive map 

```{r}
tmap_options(check.and.fix = TRUE)
tmap_mode('view')  

tm_shape(blackwood_acacia_sf) + 
  tm_dots() 
 
```

